apiVersion: v1
kind: Namespace
metadata:
  name: transmission
  labels:
    name: transmission

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-tv
  namespace: transmission
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sonarr/tv"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config
  namespace: transmission
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sonarr/config"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tv
  namespace: transmission
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: transmission
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: transmission
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
        - name: transmission-downloads
          persistentVolumeClaim:
            claimName: transmission-downloads
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: sonarr-tv
          persistentVolumeClaim:
            claimName: sonarr-tv
      containers:
      - name: sonarr
        image: linuxserver/sonarr:amd64-latest
        ports:
        - containerPort: 8989
        volumeMounts:
          - mountPath: /config
            name: sonarr-config
          - mountPath: /downloads
            name: transmission-downloads
          - mountPath: /tv
            name: sonarr-tv

---

apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: transmission
spec:
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8989

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sonarr
  namespace: transmission
spec:
  rules:
  - http:
      paths:
      - path: /sonarr
        backend:
          serviceName: sonarr
          servicePort: 80
